### ISSUE TITLE
GPU provisioning only allowed in specific DCs

### ISSUE THREAD

**Issue by tgruwell** [ibm-cloud-docs/vsi#35]
In https://cloud.ibm.com/docs/vsi/ts_capacity_bp.html (https://github.com/ibm-cloud-docs/vsi/blob/master/ts_capacity_bp.md), we should mention that GPU provisioning is only allowed in certain datacenters. Specifically: dal10, dal12, dal13, lon04, lon06, wdc07, tok02, syd04, and fra02

**Comment by William-Scott-Holmes** [comment]
Thanks for your feedback!  I have now completed a draft change in docs staging for your review:
https://test.cloud.ibm.com/docs/vsi?topic=virtual-servers-capacity-considerations
I am thinking that the UI error message improvements are in progress in the console UI side and I am happy to review them when available.
