### ISSUE TITLE
Transient still referring to two portals

### ISSUE THREAD

**Issue by jenmlin** [ibm-cloud-docs/vsi#37]
https://cloud.ibm.com/docs/vsi?topic=virtual-servers-ordering-vs-transient#before-you-begin-provisioning-transient

Should just refer to IBM Cloud Console now.

**Comment by stemke** [comment]
I removed portal and pushed these changes to staging and prod a few minutes ago. Once verified, we can close.  Thanks.

**Comment by William-Scott-Holmes** [comment]
Thanks!

**Comment by stemke** [comment]
verified... closing.  scott is removing other references as part of a different issue to check all repos.
