### ISSUE TITLE
setWebhook

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/vsi#38]
Hi There , in the following link for setting up setWebhook:
https://cloud.ibm.com/docs/vsi?topic=virtual-servers-configuring-notifications-for-reclaims-of-transient-virtual-servers

It's not clear from this doc how to setup this setWebhook in a python env. Could you please add a real example of ordering a Transient VSI and setting up setWebhook for alerting? 

We are struggling on figuring out how setup this setWebhook parameters. 

Regards
Behzad

**Comment by William-Scott-Holmes** [comment]
Moved to CFD-33 in new workspace

**Comment by William-Scott-Holmes** [comment]
I have made a request for a Python example which can be found in
https://github.com/softlayer/githubio_source/issues/302

**Comment by William-Scott-Holmes** [comment]
Hasn't this one been resolved?
