### ISSUE TITLE
There's a broken link on page https://cloud.ibm.com/docs/vsi?topic=virtual-servers-dedicated-virtual-servers

### ISSUE THREAD

**Issue by aki-k** [ibm-cloud-docs/vsi#40]
At the end of the page there's this text:

```
Next steps

After you have reviewed and decided upon your deployment options, it is time to provision your 
virtual server. To get started, see Provisioning dedicated hosts and instances.
```

The link "Provisioning dedicated hosts and instances" is broken, the link target is not found.

**Comment by William-Scott-Holmes** [comment]
Fixed broken link to now point to
/docs/vsi?topic=virtual-servers-provisioning-dedicated-hosts-instances
on two pages.
